name: Deploy the ZAB Rolebot to Kubernetes

on:
  push:
    branches: ["main"]

env:
  NODE_VERSION: "22.*" # The Node version to use.

jobs:
  push-to-registry:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:main

  deploy:
    name: Deploy to Kubernetes Cluster
    needs: push-to-registry
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to Cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tcs

      - name: Pull New Image and Restart
        run: kubectl rollout restart deployment/zab-discord-bot -n zab-prod
