name: Deploy the ZAB Rolebot to Kubernetes

on:
  push:
    branches: ["main"]

env:
  NODE_VERSION: "22.*" # The Node version to use.

jobs:
  push-to-registry:
    name: Push Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Add Version to Dockerfile
        run: sed -i 's/v0.0.0/${{ github.sha }}/g' Dockerfile

      - name: Setup Docker Builder
        uses: docker/setup-buildx-action@v2

      - name: Authenticate Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push New Image to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:main

  # deploy:
  #   name: Deploy to Kubernetes Cluster
  #   needs: push-to-registry
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  #     - name: Login to Cluster
  #       run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tcs

  #     - name: Pull New Image and Restart
  #       run: kubectl rollout restart deployment/role-bot -n zab-prod
